import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";
import { getSiteUrl } from "@/lib/env";
import "./globals.css";

const GTM_CONTAINER_ID = "GTM-KF58SSHH";

const siteUrl = getSiteUrl();

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  userScalable: true,
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "Daufuskie Island Golf Cart Rentals | Island Rental Carts – $65/Day",
  description:
    "Rent 4-seater electric golf carts on Daufuskie Island, SC. Starting at $65/day with free island-wide delivery. Book online in 2 minutes via Peek. Locally owned.",
  keywords:
    "daufuskie island golf cart rental, golf cart rental daufuskie island, daufuskie island rentals, electric golf cart daufuskie, daufuskie island transportation",
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: "Daufuskie Island Golf Cart Rentals | Island Rental Carts",
    description:
      "Rent 4-seater electric golf carts on Daufuskie Island. $65/day, free delivery, book in 2 minutes.",
    url: siteUrl,
    siteName: "Island Rental Carts",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "/images/daufuskie-island-golf-cart-rentals-og.webp",
        width: 1200,
        height: 630,
        alt: "Island Rental Carts — Daufuskie Island golf cart rentals. $65/day · Book in 2 minutes.",
      },
    ],
  },
  // Favicon and Apple touch icon are generated by app/icon.tsx and app/apple-icon.tsx (matches header logo)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="gtm-head"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','${GTM_CONTAINER_ID}');`,
          }}
        />
      </head>
      <body className="antialiased">
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=${GTM_CONTAINER_ID}`}
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
            title="Google Tag Manager"
          />
        </noscript>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
